### ISSUE TITLE
No version tags and changelog/release history available

### ISSUE THREAD

**Issue by IjzerenHein** [kiwicom/react-native-reverse-geocode#12]
Hey guys, I noticed that this lib has no changelog or github release history. This makes it difficult for users of this lib to see what has been changed/fixed and whether to upgrade or not. It would be nice when versions would be tagged (e.g. using `npm version major|minor|patch`) and then you can also add release details in the Github releases page.

cheers, keep up the good work 👍

**Comment by RobinCsl** [comment]
Hello again @IjzerenHein :) 
I guess we did not really want to bother with changelogs yet, considering it's version 0.0.5 and two days ago it was still 0.0.3. I'll try and see if I could tag the commits where we bumped the version and add some basic message.

**Comment by IjzerenHein** [comment]
Well, I guess you would't need to do it for older versions.
What I usually do myself, is add a CHANGELOG.md file when I feel the lib is mature enough to be used by others. It follows the changelog-spec, and when I create a new release I copy/paste de markdown from the CHANGELOG.md directly in the github release.
As I do here: https://github.com/IjzerenHein/react-native-magic-move/blob/master/CHANGELOG.md

**Comment by RobinCsl** [comment]
I added basic releases and tags with descriptions of what was added/fixed. 
Hopefully that helps!

We will add a CHANGELOG.md in due course. Thanks for your suggestion! 🙂

**Comment by IjzerenHein** [comment]
Awesome, great work being done on this lib :)))
Thanks Robin, cheers
