### ISSUE TITLE
We can't make it work on Android :(

### ISSUE THREAD

**Issue by ayouidaniel** [kiwicom/react-native-reverse-geocode#3]
Thanks in advance, your repo is very helpful!

We are trying to add your project but we got no luck with Android. The only response we get is "error". My only theory is that we are missing some kind of configuration in order to run Kotlin code with react native. Is there any configuration we need to add? This is the first library we add that uses Kotlin.
We followed all the linking instructions since is the same as almost any library out there that's why I think we are missing something related to Kotlin.

Any help is appreciated :D thanks!

PS: iOS works like a charm!

**Comment by tbergq** [comment]
Hi, and thanks for showing interest in this repo. 

I just started a new project with `react-native init` and did `yarn install` & `react-native link` and it worked. 

Do you have a link to the repo where you are trying to use this?

Also it sounds to me like this error comes from our code. I expect missing kotlin setup would cause build error 🤔 

```
} catch (e: Exception) {
      callback.invoke("error", null)
    }
```
We could maybe improve this catch block to give a better error, what do you think @RobinCsl

**Comment by tbergq** [comment]
@ayouidaniel, we just released a new version to npm, `0.0.3`. It should have a better error-message. Could you please update to this version, run the project and see what error message you get?

**Comment by ayouidaniel** [comment]
Thanks after some research and testing it was not something related to `react-native link` neither any configuration related to Kotlin. Actually the library integration was ok but as mentioned before the error we got was not so helpful. Actually I made the same change as you did in order to debug. I was going to open the PR but thanks! 🥳

Right now I'm facing different response from iOS and Android with the same info. But let me check what's happening and if I find the way to improve it I will send you a PR. 

Thanks again guys!

**Comment by RobinCsl** [comment]
> Right now I'm facing different response from iOS and Android with the same info. But let me check what's happening and if I find the way to improve it I will send you a PR.

Could you make that more precise? I would be curious as what the different responses are? If it's about the addresses and places it gives you, I noticed too that Android and iOS do reverse geocoding differently. 

If there are any ways the documentation can be improved, etc. feel free to submit a PR!
Thank you 😃
