### ISSUE TITLE
Error in function searchForLocations, undefined. Library still supported? 

### ISSUE THREAD

**Issue by flancast90** [kiwicom/react-native-reverse-geocode#32]
Hello, 

While attempting to use your library in React Native, as shown in the example, I received the below error message:
```react
Cannot read property 'searchText' of undefined
  Evaluating App.js
  Loading App.js
TypeError: Cannot read property 'searchText' of undefined
    at Object.eval (App.js.js:14:14

    at eval (App.js.js

    at eval (App.js.js

    at eval (<anonymous>)
    at [snack internals]
    at Object.a ([snack internals]
    at e.evaluate ([snack internals]
    at Ze ([snack internals]
    at [snack internals]
    at https://snack-web-player.s3.us-west-1.amazonaws.com/v2/42/static/js/app.056cc19a.chunk.js:1:14427
```
I have confirmed that this is a legitimate issue, as by receiving the same issue with both my custom code and the exact same code provided in the README.md. I am just a beginner in React Native, and am probably missing simple, but I would really appreciate if someone could spend the time to help me with this. 

Thanks so much!

**Comment by RobinCsl** [comment]
Hello @flancast90,

Thanks for your interest in this library! It has not been maintained for a while, so I'm not sure how well it aged.

As for your issue, I would recommend adding a reproduction repository/example.

Judging by the log you attached, it seems you are using Expo Snack and I don't know well it handles native dependencies written in Objective C and Kotlin.

A reproduction would be super useful to help you further.

**Comment by flancast90** [comment]
Thanks for your help, @RobinCsl. 
I originally just started off with the code on the README.md example, and have modified it as shown below.
```react
import React from 'react';
import { Text, View } from 'react-native';
import RNReverseGeocode from '@kiwicom/react-native-reverse-geocode';

const region = {
  latitude: 50,
  longitude: 14,
  latitudeDelta: 0.01,
  longitudeDelta: 0.01,
};

const searchText = 'Charles';
var jsonData;

const reverse_geocode = () => {
  RNReverseGeocode.searchForLocations(
    searchText,
    region,
    (err, res) => {
      jsonData = {
        error: err,
        addresses: res
      }
    }
  );
};

const app = () => {
  reverse_geocode();
  return (
    <View>
      <Text>{jsonData}</Text>
    </View>
  );
};

export default app;
```
What I am trying to accomplish is to update the value of ``jsonData`` with the JSON output by the searchForLocations() function of this library. The issue seems to be that I do not quite understand the syntax of the function call, and, as I said earlier, am just starting to learn react-native.

Thank you in advance!

**Comment by RobinCsl** [comment]
@flancast90, if you're using Snack Expo, it might be impossible.

Here's an example repository of how to make it work with iOS at least (I did not test on Android):

https://github.com/RobinCsl/example-kiwicom-react-native-reverse-geocode

Hope this helps!

(If you're starting with React Native, I'd recommend checking the React docs about hooks for functional components! I included an example of how to use the library with the `useEffect` hook.)

**Comment by flancast90** [comment]
Thanks for the great example repo!
Unfortunately, the code shown in the reproducible example is not working for me. Instead, I receive this error message:
```react
null is not an object (evaluating 'RNReverseGeocode.searchForLocations')

const [jsonData, setJsonData] = React.useState(null);
React.useEffect(() => {
>   RNReverseGeocode.searchForLocations(
                    ^
     searchText,
     region,
     (err, res) => {
```
We seem to be making progress, however, this error message is different than the last!

I am now using the expo CLI, etc, as shown in the example demo. The testing was done through barcode scan on the ExpoGo app on my iPhone.

**Comment by RobinCsl** [comment]
> The testing was done through barcode scan on the ExpoGo app on my iPhone.

Yes, exactly, ExpoGo will probably not be enough without further work on the setup.

I believe the Expo team just released a new way to use other native modules (i.e. modules like this one shipping with code written in Objective C/Swift for iOS and/or Java/Kotlin for Android), but the demo repo is not using the Expo CLI to run the app.

> We seem to be making progress, however, this error message is different than the last!

A new error usually means progress, yes :)

I would encourage you to clone the repository and try and follow the instructions in the README. You will need to have an emulator/simulator handy or a cable from a macOS system to your iPhone. (If you go beyond ExpoGo like in this case, you will need macOS to develop iOS apps sadly).

**Comment by flancast90** [comment]
Ok. I should be able to connect Expo to my Android Studio Emulator. Thanks
for your help (and time).

I will let you know how it goes!

**Comment by flancast90** [comment]
I have just successfully connected to my Android Studio emulator, and launched the project, but am still receiving the error from before (attached screenshot now):

![](https://i.imgur.com/LpZ0f9I.png)


Any ideas? Perhaps I will have to boot in iOS, but that kind of defeats the purpose of a cross-platform app like I am working on developing.

**Comment by RobinCsl** [comment]
From what I see, you did not clone the repository and instead only copy-pasted the contents of `App.js` into an Expo initialised application with the "managed workflow".

**This package will not work in that "managed workflow" setup.**

You need to use the "bare workflow" instead. If you don't want to clone the example repository, one way to get to it should be to use `expo eject` in your project and the `ios/` and `android/` folders should be visible in your file tree. But cloning the example repo should be easier.

I tested it on my Android emulator too, and it worked fine! (I just had to replace `searchText`'s value with "Charles Bridge" for some results to be returned)

<p align="center">
<img src="https://user-images.githubusercontent.com/22741774/127453031-f2207df0-dfe9-4193-97ea-e86f77f0cee7.png" width="400" />
</p>

**Comment by flancast90** [comment]
Thanks so much!

I’ll test that as soon as I am back to my computer. You are right about it
being in a “managed workflow.” For some reason the “bare workflow” setup
returned an npm/node issue, which I didn’t feel like fixing at the time,
and was just solved using a (modified) typescript setup.

**Comment by flancast90** [comment]
Wonderful! It works perfectly. 

I'm sorry for being such a bother with my beginner questions, and really appreciate your help in this matter! I would love to credit you in my app, when it is completed, if that is OK.

What finally ended up working was following the 'run in android' instructions from [This Post](https://stackoverflow.com/questions/50396270/running-on-device-from-android-studio-run-option-instead-of-react-native-run-an), along with the instructions for the "bare-minimal" setup you gave.

Thanks again!

**Comment by RobinCsl** [comment]
Great to hear you got it working too!! 🎉 

> I'm sorry for being such a bother with my beginner questions

Don't be sorry :) We're all beginners in different topics and when one teaches, two learn ;)

> I would love to credit you in my app, when it is completed, if that is OK.

Sure, keep me in the loop :) Would love to see what you're building.

All the best.
