### ISSUE TITLE
Sometimes duplicate results are returned on Android

### ISSUE THREAD

**Issue by IjzerenHein** [kiwicom/react-native-reverse-geocode#8]
This occurs when you search for a landmark nearby, and type the name of that landmark entirely. 
The reason is that on Android two searches are performed, and if the first "localized" search returns less than 10 items, then another "remote" search is performed which also returns that result.
There should be some filtering of duplicates here.

![image](https://user-images.githubusercontent.com/6184593/53887265-3b54f500-4022-11e9-918a-da2ef6710ae6.png)

**Comment by IjzerenHein** [comment]
Similarly, I'll try to submit a PR for it

**Comment by RobinCsl** [comment]
Sounds good! Thank you for submitting another issue! 🎉

**Comment by IjzerenHein** [comment]
Hi Robin!

Just a quick question, I noticed in the Android code that the remote and local results are concatenated, but the remote results are placed in front of the local results. I would have assumed that the local results have priority over the remote results, so I would have figured that this should be the other way around. Or is there a specific reason for this?

Current:
```val addresses = remoteAddresses.orEmpty() + localAddresses.orEmpty()```

cheers

**Comment by IjzerenHein** [comment]
Fixed by PR #10

**Comment by IjzerenHein** [comment]
Correction, fixed by PR #11

**Comment by RobinCsl** [comment]
> I would have assumed that the local results have priority over the remote results, so I would have figured that this should be the other way around. Or is there a specific reason for this?

I cannot remember why I chose that approach. Your request seems totally reasonable to me. I will review your PR tomorrow. Thanks again!

**Comment by IjzerenHein** [comment]
Sweet!
